config/routes.rb
TntApp::Application.routes.draw do

  resources :line_items

  resources :carts

  get "store/index"

  resources :products

  root :to => 'store#index'

  match '/example',    to: 'bootstrap#home'

  match '/purchase',   to: 'carts#purchase'

  match '/product/boverear',  to: 'product#boverear'
  match '/product/bearbuds',  to: 'product#bearbuds'
  match '/product/bactive',   to: 'product#bactive'

  match '/confirm', to: 'confirm#confirm'
  

end

app/controllers/bootstrap_controller.rb
class BootstrapController < ApplicationController
	def home
		@boverear = Product.find(7)
	end
end

app/helpers/bootstrap_helper.rb
module BootstrapHelper
end

app/views/bootstrap/example.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bootstrap 101 Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#">Ear City</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li class="divider"></li>
                  <li class="nav-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
            </ul>
            <form class="navbar-form pull-right">
              <input class="span2" type="text" placeholder="Email">
              <input class="span2" type="password" placeholder="Password">
              <button type="submit" class="btn">Sign in</button>
            </form>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="mboxDefault">
        <div class="hero-unit">
          <h1>Welcome to Ear City!</h1>
          <p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
          <p><a href="#" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
        </div>
      </div>
      <script type="text/javascript">
        mboxCreate('tntapp_hero')  
      </script>
   

      <!-- Example row of columns -->
      <div class="row">
        <div class="mboxDefault">
          <div class="span4">
            <h2 class="box">Over Ear</h2>
            <img src="/assets/overear1.jpeg">
            <a class="btn box" href="#">View details &raquo;</a>
          </div>
        </div>
        <script type="text/javascript">
          mboxCreate('tntapp_box1')  
        </script>
        
        <div class="mboxDefault">
          <div class="span4">
            <h2 class="box">Earbuds</h2>
            <img src="/assets/buds1.jpeg">
            <p><a class="btn box" href="#">View details &raquo;</a></p>
          </div>
        </div>
        <script type="text/javascript">
          mboxCreate('tntapp_box2')  
        </script>

        <div class="mboxDefault">
          <div class="span4">
            <h2 class="box">Active</h2>
            <img src="/assets/active1.jpeg">
            <p><a class="btn box" href="#">View details &raquo;</a></p>
          </div>
         </div>
        <script type="text/javascript">
          mboxCreate('tntapp_box3')  
        </script>  
      </div>

      <hr>

      <footer>
        <p></p>
      </footer>

    </div>
  </body>
</html>

app/views/bootstrap/home.html.erb
    <div class="container">

      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="mboxDefault">
        <div class="hero-unit">
          <h1>Welcome to Ear City!</h1>
          <p>The home of headphone greatness. Make sure to check out our product reviews and find the right product for your lifestyle and budget.</p>
        </div>
      </div>
      <script type="text/javascript">
        mboxCreate('tntapp_hero', 'site=us','earbuds=true')  
      </script>
   

      <!-- Example row of columns -->
      <div class="row">
        <div class="mboxDefault">
          <div class="span4">
            <h2 class="box">Over Ear</h2>
            <img src="/assets/b-overear.jpeg">
            <%= link_to 'View Details', product_boverear_path, :class => 'btn box' %>
          </div>
        </div>
        <script type="text/javascript">
          mboxCreate('tntapp_box1')  
        </script>
        
        <div class="mboxDefault">
          <div class="span4">
            <h2 class="box">Earbuds</h2>
            <img src="/assets/b-buds.jpeg">
            <%= link_to 'View Details', product_bearbuds_path, :class => 'btn box' %>
          </div>
        </div>
        <script type="text/javascript">
          mboxCreate('tntapp_box2')  
        </script>

        <div class="mboxDefault">
          <div class="span4">
            <h2 class="box">Active</h2>
            <img src="/assets/b-active.png">
            <%= link_to 'View Details', product_bactive_path, :class => 'btn box' %>
          </div>
         </div>
        <script type="text/javascript">
          mboxCreate('tntapp_box3')  
        </script>  
      </div>

      <hr>

      <footer>
        <p></p>
      </footer>

    </div>